name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.3
        with:
          linter: flake8

  discord:
    enviroment: secrets
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
